"""
Shared NSE ticker symbol map.
Keys are script names as they appear in trades.json (output of import_all.norm()).
Values are clean NSE ticker symbols.
Used by telegram_bot.py (display) and vm_sync_gsheet.py (GOOGLEFINANCE formulas).
"""
import re as _re

_SUFFIX_RE = _re.compile(
    r'\s+(LIMITED|LTD\.?|CO\.?\s*LTD\.?|CORP\.?|PVT\.?|INC\.?|INDUSTRIES|IND\.?)\.?$',
    _re.IGNORECASE
)

SYMBOL_MAP = {
    "ALKYL AMINES":"ALKYLAMINE","BALKRISHNA IND":"BALKRISIND",
    "BHARAT COKING COAL":"BHARATCOAL","BHARAT ELECTRONICS":"BEL",
    "BOMBAY BURMAH TRADING":"BBTC","CAMS":"CAMS","CANARA BANK":"CANBK",
    "CENTURY PLYBOARDS":"CENTURYPLY","CHOLAMANDALAM":"CHOLAFIN",
    "COFORGE":"COFORGE","DATA PATTERNS":"DATAPATTNS","DATA PATTERNS INDIA":"DATAPATTNS","DATAPATTERNSINDIA":"DATAPATTNS","EIMCOELECONINDIA":"EIMCOELECO","EIMCO ELECON INDIA":"EIMCOELECO",
    "HAVELLS INDIA":"HAVELLS","HAVELLSINDIA":"HAVELLS",
    "DELHIVERY":"DELHIVERY","DEVYANI INTERNATIONAL":"DEVYANI",
    "DIXON TECHNOLOGIES":"DIXON","DOMS INDUSTRIES":"DOMS",
    "EMMVEE PHOTOVOLTAIC":"EMMVEE","EQUITAS SMALL FIN BANK":"EQUITASBNK",
    "EICHER MOTORS":"EICHERMOT","EXIDE INDUSTRIES":"EXIDEIND",
    "FORTIS HEALTHCARE":"FORTIS","GARWARE TECH FIBRES":"GARFIBRES",
    "GMR AIRPORTS":"GMRAIRPORT","GODREJ INDUSTRIES":"GODREJIND",
    "GODREJ PROPERTIES":"GODREJPROP","GRAPHITE INDIA":"GRAPHITE",
    "GRINDWELL NORTON":"GRINDWELL","HDFC BANK":"HDFCBANK",
    "HIMADRI SPECIALITY CHEM":"HSCL","HINDUSTAN COPPER":"HINDCOPPER",
    "HINDUSTAN ZINC":"HINDZINC","IDBI BANK":"IDBI",
    "IDFC FIRST BANK":"IDFCFIRSTB","IIFL FINANCE":"IIFL",
    "IFCI":"IFCI","INDIAN ENERGY EXCHANGE":"IEX",
    "INDIAN HOTELS":"INDHOTEL","INDOCO REMEDIES":"INDOCO",
    "INFOSYS":"INFY","INTELLECT DESIGN ARENA":"INTELLECT",
    "INTERGLOBE AVIATION":"INDIGO","INOX WIND":"INOXWIND",
    "ITC":"ITC","JBM AUTO":"JBMA","JM FINANCIAL":"JMFINANCIL",
    "JSW ENERGY":"JSWENERGY","JUPITER WAGONS":"JUPITERWAG",
    "KALPATARU":"KALPATARU","KALPATARU PROJECTS":"KPIL",
    "KAYNES TECHNOLOGY":"KAYNES","KPIT TECHNOLOGIES":"KPITTECH",
    "L&T TECHNOLOGY SERVICES":"LTTS","LAURUS LABS":"LAURUSLABS",
    "LIC":"LICI","LUPIN":"LUPIN","M&M FINANCE":"M&MFIN",
    "MAX HEALTHCARE INS LTD":"MAXHEALTH","MAZAGON DOCK":"MAZDOCK",
    "MIRAE ENERGY ETF":"MAFANG","MIRAEAMC MAGOLDETF":"GOLDETF",
    "MIC ELECTRONICS":"MICEL","MOSCHIP TECHNOLOGIES":"MOSCHIP",
    "MRPL":"MRPL","MSTC":"MSTCLTD","NATCO PHARMA":"NATCOPHARM",
    "NELCO":"NELCO","NETWEB TECHNOLOGIES":"NETWEB",
    "NEWGEN SOFTWARE":"NEWGEN","NIMBUS AGRI":"NIMBUS",
    "NIPPON ETF IT":"ITBEES","NIPPON ETF LIQUID BEES":"LIQUIDBEES",
    "NIPPON LIFE AMC":"NAM-INDIA","NIPPON NETFSILVER":"SILVERBEES",
    "NMDC":"NMDC","NTPC":"NTPC","OBEROI REALTY":"OBEROIRLTY",
    "ORACLE FINANCIAL SERVICES":"OFSS","PARADEEP PHOSPHATES":"PARADEEP",
    "PERSISTENT SYSTEMS":"PERSISTENT","PG ELECTROPLAST":"PGEL",
    "PI INDUSTRIES":"PIIND","PIRAMAL PHARMA":"PPLPHARMA",
    "POONAWALLA FINCORP":"POONAWALLA","REC":"RECLTD",
    "REDINGTON":"REDINGTON","RELIANCE INDUSTRIES":"RELIANCE",
    "SAGILITY LIMITED":"SAGILITY","SAMVARDHANA MOTHERSON":"MOTHERSON",
    "SHAILY ENGINEERING":"SHAILY","SOUTH INDIAN BANK":"SOUTHBANK",
    "SPANDANA SPHOORTY":"SPANDANA","SUZLON ENERGY":"SUZLON",
    "SUN PHARMACEUTICAL":"SUNPHARMA","SUN PHARMA":"SUNPHARMA",
    "TANLA PLATFORMS":"TANLA","TCS":"TCS",
    "TEJAS NETWORKS":"TEJASNET","TRANSPORT CORP OF INDIA":"TCI",
    "VARUN BEVERAGES":"VBL","VST INDUSTRIES":"VSTIND",
    "WHIRLPOOL INDIA":"WHIRLPOOL","WIPRO":"WIPRO",
    "WOCKHARDT":"WOCKPHARMA","ZEN TECHNOLOGIES":"ZENTEC",
    "ZENSAR TECHNOLOGIES":"ZENSARTECH","ANGEL ONE":"ANGELONE",
    "BANK OF INDIA":"BANKINDIA","BLUE JET HEALTHCARE":"BLUEJET",
    "ALEMBIC PHARMA":"APLLTD","ASHAPURA MINECHEM":"ASHAPURMIN",
    "GUJARAT NARMADA FERT":"GNFC","ZYDUS LIFESCIENCES":"ZYDUSLIFE",
    "INOXWIND":"INOXWIND","KPIL":"KPIL","BAJAJ HOUSING FINANCE":"BAJAJHFL",
    "PREMIER ENERGIES":"PREMIERENE","AVENUE SUPERMARTS":"DMART",
    "BSE":"BSE","LARSEN & TOUBRO":"LT","NIIT":"NIITLTD",
    "POWER FIN CORP":"PFC","K.P.R.MILL":"KPRMILL",
    "ELGI EQUIPMENTS":"ELGIEQUIP","IRB INFRA DEV":"IRBINFRA",
    "PHOENIX MILLS":"PHOENIXLTD","BANK OF MAHARASHTRA":"MAHABANK",
    "MMTC":"MMTC","CHOLAHLDNG":"CHOLAHLDNG","BALKRISIND":"BALKRISIND",
    "ETERNAL":"ETERNAL","FEDERAL BANK":"FEDERALBNK",
    "GRANULES INDIA":"GRANULES","GRASIM INDUSTRIES":"GRASIM",
    "ICICI BANK":"ICICIBANK","INDUS TOWERS":"INDUSTOWER",
    "INFO EDGE (I)":"NAUKRI","INFO EDGE":"NAUKRI",
    "KOTAK MAHINDRA BANK":"KOTAKBANK","MAHINDRA & MAHINDRA":"M&M",
    "MAHINDRA LIFESPACE DEV":"MAHLIFE","MAHINDRA LIFESPACE":"MAHLIFE",
    "MINDA CORPORATION":"MINDACORP",
    "ONE 97 COMMUNICATIONS":"PAYTM","PNB HOUSING FIN":"PNBHOUSING","PNB HOUSING FINANCE":"PNBHOUSING",
    "PRESTIGE ESTATE":"PRESTIGE","PRESTIGE ESTATES":"PRESTIGE",
    "SBI LIFE INSURANCE CO":"SBILIFE","SBI LIFE INSURANCE":"SBILIFE",
    "SHRIRAM FINANCE":"SHRIRAMFIN","STATE BANK OF INDIA":"SBIN",
    "SUPRIYA LIFESCIENCE":"SUPRIYA","SWIGGY":"SWIGGY",
    "SYNGENE INTERNATIONAL":"SYNGENE","TATA COMMUNICATIONS":"TATACOMM",
    "TATA POWER CO":"TATAPOWER","TATA POWER":"TATAPOWER","TATA STEEL":"TATASTEEL",
    "TECH MAHINDRA":"TECHM","UNITED SPIRITS":"MCDOWELL-N","VARROC ENGINEERING":"VARROC",
    "ZERODHAAMC - LIQUIDCASE":"LIQUIDCASE",
    "INDIAN RAILWAY FIN CORP L":"IRFC","INDIAN RAILWAY FIN CORP":"IRFC","INDIAN RAILWAY FINANCE":"IRFC",
    "LUPIN LTD.":"LUPIN","PARADEEP PHOSPHATES":"PARADEEP","AARTI INDUSTRIES":"AARTIIND",
    "DR. REDDY S LABORATORIES":"DRREDDY","DR. REDDY'S LABORATORIES":"DRREDDY",
    "TATA MOTORS":"TATAMOTORS",
    # exact names as they appear in trades.json (output of import_all.norm())
    "BHARAT ELECTRONICS LTD.":"BEL","BHARAT ELECTRONICS LTD":"BEL",
    "HINDUSTAN AERONAUTICS LIMITED":"HAL","HINDUSTAN AERONAUTICS LTD":"HAL",
    "ADANI PORT & SEZ LTD":"ADANIPORTS","ADANI PORTS & SEZ LTD":"ADANIPORTS","ADANI PORTS & SEZ LTD.":"ADANIPORTS",
    "ADITYA BIRLA LIFES BRAN L":"ABLBL",
    "AETHER INDUSTRIES LIMITED":"AETHER","AETHER INDUSTRIES LTD":"AETHER",
    "BAJAJ HOUSING FINANCE LIMITED":"BAJAJHFL",
    "BIRLASOFT LIMITED":"BSOFT","BIRLASOFT LTD":"BSOFT",
    "CROMPT GREA CON ELEC LTD":"CROMPTON","CROMPTON GREAVES CONSUMER":"CROMPTON",
    "CITY UNION BANK LTD":"CUB","CITY UNION BANK LIMITED":"CUB","CITY UNION BANK":"CUB",
    "CLEAN SCIENCE & TECH LTD":"CLEAN","CLEAN SCIENCE & TECH":"CLEAN",
    "CENTRAL DEPO SER (I) LTD":"CDSL","CENTRAL DEPO SER (I)":"CDSL",
    "BEML LIMITED":"BEML","BEML LTD":"BEML","BEML":"BEML",
    "KAVERI SEED CO. LTD.":"KSCL","KAVERI SEED CO LTD":"KSCL","KAVERI SEED":"KSCL",
    "RITES LIMITED":"RITES","RITES LTD":"RITES","RITES":"RITES",
    "PARAS DEF AND SPCE TECH L":"PARAS","PARAS DEFENCE AND SPACE TECH":"PARAS","PARAS DEFENCE":"PARAS",
    "BALKRISHNA INDUSTRIES LTD.":"BALKRISIND","BALKRISHNA INDUSTRIES LTD":"BALKRISIND","BALKRISHNA INDUSTRIES":"BALKRISIND",
    "KFIN TECHNOLOGIES LIMITED":"KFINTECH","KFIN TECHNOLOGIES LTD":"KFINTECH","KFIN TECHNOLOGIES":"KFINTECH",
    "HCL TECHNOLOGIES LTD":"HCLTECH","HCL TECHNOLOGIES LTD.":"HCLTECH","HCL TECHNOLOGIES":"HCLTECH",
    "THOMAS COOK (INDIA) LTD":"THOMASCOOK","THOMAS COOK INDIA LTD":"THOMASCOOK","THOMAS COOK (INDIA)":"THOMASCOOK",
    "OLECTRA GREENTECH LTD":"OLECTRA","OLECTRA GREENTECH LIMITED":"OLECTRA","OLECTRA GREENTECH":"OLECTRA",
    "CARBORUNDUM UNIVERSAL LTD":"CARBORUNIV","CARBORUNDUM UNIVERSAL LIMITED":"CARBORUNIV","CARBORUNDUM UNIVERSAL":"CARBORUNIV",
    "COROMANDEL INTERNTL.":"COROMANDEL","COROMANDEL INTERNATIONAL":"COROMANDEL",
    "EDELWEISS FIN SERV":"EDELWEISS","EDELWEISS FINANCIAL SERVICES":"EDELWEISS",
    "KIRLOSKAR OIL ENG":"KIRLOSENG","KIRLOSKAR OIL ENGINES":"KIRLOSENG",
    "KNR CONSTRU":"KNRCON","KNR CONSTRUCTIONS":"KNRCON",
    "MAX HEALTHCARE INS":"MAXHEALTH",
    "NACL INDUSTRIES":"NACLIND",
    "RAILTEL CORP OF IND":"RAILTEL","RAILTEL CORPORATION":"RAILTEL",
    "THE NEW INDIA ASSU":"NIACL","NEW INDIA ASSURANCE":"NIACL",
    "TRANS & RECTI.":"TARIL","TRANSFORMERS AND RECTIFIERS":"TARIL",
    "ZEE ENTERTAINMENT ENT":"ZEEL","ZEE ENTERTAINMENT":"ZEEL",
    "ACME SOLAR HOLDINGS":"ACMESOLAR",
    "HDFC LIFE INS":"HDFCLIFE","HDFC LIFE INSURANCE":"HDFCLIFE",
    "SCHAEFFLER INDIA":"SCHAEFFLER",
    "ADITYA BIRLA LIFES BRAN":"ABLBL","ADITYA BIRLA LIFESTYLE BRANDS":"ABLBL",
    "KPR MILL":"KPRMILL","NCC":"NCC","NOCIL":"NOCIL",
    "SAGILITY":"SAGILITY","UCO BANK":"UCOBANK","SWAN CORP":"SWANCORP",
    "CROMPT GREA CON ELEC":"CROMPTON",
    # Sumitomo
    "SUMITOMO CHEM INDIA":"SUMICHEM","SUMITOMO CHEMICALS INDIA":"SUMICHEM",
    "SHIPPING CORP OF INDIA":"SCI","SHIPPING CORPORATION OF INDIA":"SCI",
    "RAVINDRA ENERGY":"RELTD","RAVINDRA ENERGY LTD":"RELTD","RAVINDRAENERGY":"RELTD",
    "CANARA ROBECO ASSET MANAGEMENT":"CRAMC",
    # Previously resolved via fallback — added to prevent future #N/A if re-bought
    "AEGIS LOGISTICS":"AEGISLOG","ALOK INDUSTRIES":"ALOKINDS",
    "ARVIND FASHIONS":"ARVINDFASN","ASIAN PAINTS":"ASIANPAINT",
    "BERGER PAINTS (I)":"BERGEPAINT","BHARAT HEAVY ELECTRICALS":"BHEL",
    "HINDUSTAN AERONAUTICS LIMITED":"HAL","HINDUSTAN AERONAUTICS":"HAL",
    "LAURUS LABS":"LAURUSLABS","PCBL CHEMICAL":"PCBL",
    "PUNJAB NATIONAL BANK":"PNB","THE PHOENIX MILLS":"PHOENIXLTD",
    "THE SOUTH INDIAN BANK":"SOUTHBANK","URBAN COMPANY":"URBAN",
    "VA TECH WABAG":"WABAG","WAAREE RENEWABLE TECH":"WAAREERENEW",
    "TATA MOTORS PASS VEH":"TATAMTRDVR","TEXMACO RAIL & ENG.":"TEXRAIL",
    "SIEMENS ENERGY INDIA":"SIEMENSENGY","OSWAL PUMPS":"OSWALPUMP",
    "ICICI PRUDENTIAL GOLD ETF":"IPGETF",
    # Exact CBOS script names that must survive without ticker_overrides.json
    "EPACK PREFAB TECHN":"EPACKPEB","EPACK PREFAB TECH":"EPACKPEB","EPACK PREFAB":"EPACKPEB",
    "COHANCE LIFESCIENCES":"COHANCE","COHANCE LIFE SCIENCES":"COHANCE",
    "WATERWAYS LEISURE TOUR L":"CORDELIA","WATERWAYS LEISURE TOUR":"CORDELIA","WATERWAYS LEISURE":"CORDELIA",
}


def resolve(script: str, overrides: dict) -> str:
    """
    Resolve a CBOS script name to a clean NSE ticker.
    Check order: overrides → SYMBOL_MAP → suffix-stripped SYMBOL_MAP → strip non-alphanum.
    """
    s = script.strip()
    su = s.upper()
    # Build case-insensitive overrides lookup
    overrides_upper = {k.upper(): v for k, v in overrides.items()}
    # 1. User overrides take priority (case-insensitive)
    if su in overrides_upper:
        v = overrides_upper[su]
        if v:
            return v.strip().upper().replace(".NS", "")
    # 2. Direct map lookup
    if su in SYMBOL_MAP:
        return SYMBOL_MAP[su]
    # 3. Suffix-stripped lookup
    stripped = _SUFFIX_RE.sub('', su).strip()
    if stripped != su and stripped in SYMBOL_MAP:
        return SYMBOL_MAP[stripped]
    # 4. Fallback: strip all non-alphanumeric (keep &)
    return _re.sub(r'[^A-Z0-9&]', '', su)
